### ISSUE TITLE
not work for some free apps

### ISSUE THREAD

**Issue by jr3074** [yan12125/google-play-downloader#3]
i can't download some apps like real racing 3 (free). But i can download the others like line, WA.
here is output real racing 3:
server@server:~/gp$ python gplay-downloader.py -n com.ea.games.r3_row

```
    GooglePlay Downloader - Directly download apks from GooglePlay to your PC.
    Copyleft Simone Margaritelli <evilsocket@evilsocket.net>
    http://www.evilsocket.net
```

@ Logging in ...
@ Requesting package ...
Traceback (most recent call last):
  File "gplay-downloader.py", line 127, in <module>
    main()
  File "gplay-downloader.py", line 118, in main
    (url, market_da) = market.get_asset(request.encode())
  File "/home/server/gp/Market.py", line 55, in get_asset
    raise Exception("Unexpected response.")
Exception: Unexpected response.

**Comment by yan12125** [comment]
Confirmed, while I don't know the cause :(

**Comment by yan12125** [comment]
The original device name is 'passion', which is not compatible with com.ea.games.r3_row. Now I set the default device name to 'hammerhead', which works for me.

**Comment by jr3074** [comment]
yeah it works now, great
