### ISSUE TITLE
obb

### ISSUE THREAD

**Issue by voobl** [yan12125/google-play-downloader#4]
You could download
  obb ???

**Comment by yan12125** [comment]
Sorry not quite understand. What does "obb" mean?

**Comment by voobl** [comment]
http://www.onyxbits.de/raccoon  

http://im90.gulfup.com/ZElgDd.png
http://im90.gulfup.com/WcOoa9.png

**Comment by yan12125** [comment]
Thanks. I'll investigate the feature these days.

**Comment by voobl** [comment]
hi

Is there any news ?

Thanks

**Comment by yan12125** [comment]
Stucked. I've tried Raccoon and it does not download OBB.

**Comment by voobl** [comment]
Raccoon works well with me

I can download

obb
There is no application to her facility obb file

**Comment by yan12125** [comment]
This tool is abandoned. Closing.
