### ISSUE TITLE
It no longer works

### ISSUE THREAD

**Issue by voobl** [yan12125/google-play-downloader#5]
Hello, how are you

It no longer works
It has stopped working. Can you check again?

Thank you

**Comment by yan12125** [comment]
Thanks fixed!

**Comment by voobl** [comment]
Thank you
It works well now thanks again for the wonderful work

You can fetch the application data to json
Title
Description
Size
.....

I badly need him

**Comment by yan12125** [comment]
Could you open a new issue for that?
