### ISSUE TITLE
Google play update ?

### ISSUE THREAD

**Issue by climb2211** [yan12125/google-play-downloader#8]
now downloader error,zlib.decompress(data, 16 + zlib.MAX_WBITS) ,Decompression is empty，i don't know why

**Comment by yan12125** [comment]
Confirmed this is broken :(

**Comment by yan12125** [comment]
Seems the new API has been out in the wild for 2 years. https://github.com/mmcloughlin/finsky can be a good starting point on switching to the new API.

**Comment by yan12125** [comment]
Update: Google also abandons the old login API and forces OAuth2.

An interesting idea: https://github.com/Lekensteyn/apk-downloader/issues/22#issuecomment-119000070
> I suggest to perform a SSL MitM against the Android device and attempt a registration from that.

**Comment by yan12125** [comment]
I don't think I have time on fixing this, and there's already a great alternative at https://github.com/matlink/gplaycli. Closing.
