### ISSUE TITLE
You can solve the problem  thank you In advance  It no longer works

### ISSUE THREAD

**Issue by voobl** [yan12125/google-play-downloader#9]
You can solve the problem

thank you In advance

It no longer works

Traceback (most recent call last):
  File "gplay-downloader.py", line 115, in <module>
    main()
  File "gplay-downloader.py", line 99, in main
    market.login()
  File "/home/marketapk/public_html/downloader/Market.py", line 30, in login
    raise Exception("Invalid login credentials.")
Exception: Invalid login credentials.

**Comment by yan12125** [comment]
Sorry but this project is completely broken as Google abandons the old API. See #8. Most likely fixing it requires rewriting almost the whole project and I don't have that much time for such a big task.

**Comment by voobl** [comment]
Please help me please please
I desperately need him

  I have no alternative
Please correct the code

I have a website that works on this
It will not work
Will stop

Please
  Please

**Comment by yan12125** [comment]
If I knew how to fix this, I would do it immediately.

> I have no alternative

There are tons of open source APK downloaders and some are also in Python. https://github.com/matlink/gplaycli seems promising.

**Comment by voobl** [comment]
I tried to run it but did not work with me on centos   gplaycli
